/* SPDX-License-Identifier: MIT */
/* Copyright (c) 2026 huienming */

#include "device_model.h"

/*
 * 设备模型（**唯一出处**）：五个语言的设备端示例都编译/链接这一份，
 * 分发时不依赖任何外部模型文件。
 *
 * 一台数控机床：X/Y/Z/C 四个进给轴 + 主轴 S + 数控系统（CONTROLLER）。
 * 每个轴一个功率 /AXIS@<轴>/POWER@1 与**三个加速度**
 * /AXIS@<轴>/ACCELERATION@X|Y|Z —— 振动信号在 X/Y/Z 三个方向上的分量
 * （方向写在数据项的 number 里，路径就是 /AXIS@<轴>/ACCELERATION@<方向>）。
 * 采样通道两个：sample_channel0（1 s / 1 s，运行状态八项）与
 * EdgeSersors（1 ms / 100 ms：5 个功率 + 15 个加速度，振动每槽 4 点 =
 * 0.25 ms 一位，即 MANUAL 4.5 的亚毫秒采样）。
 */
static const char kDeviceModel[] =
    "{\n"
    "  \"id\": \"01\",\n"
    "  \"type\": \"NC_LINK_ROOT\",\n"
    "  \"name\": \"机床模型文件\",\n"
    "  \"version\": \"1.1.0\",\n"
    "  \"devices\": [\n"
    "    {\n"
    "      \"type\": \"MACHINE\",\n"
    "      \"id\": \"0103\",\n"
    "      \"name\": \"数控机床\",\n"
    "      \"description\": \"数控机床\",\n"
    "      \"version\": \"1.0\",\n"
    "      \"configs\": [\n"
    "        {\n"
    "          \"id\": \"sample_channel0\",\n"
    "          \"type\": \"SAMPLE_CHANNEL\",\n"
    "          \"name\": \"机床运行状态\",\n"
    "          \"sampleInterval\": 1000,\n"
    "          \"uploadInterval\": 1000,\n"
    "          \"ids\": [\n"
    "            {\n"
    "              \"id\": \"010307\"\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"010305\"\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035409\"\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035413\"\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035509\"\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"010302\"\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"010309\"\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035412\"\n"
    "            }\n"
    "          ]\n"
    "        },\n"
    "        {\n"
    "          \"id\": \"EdgeSersors\",\n"
    "          \"type\": \"SAMPLE_CHANNEL\",\n"
    "          \"name\": \"边缘传感器\",\n"
    "          \"sampleInterval\": 1,\n"
    "          \"uploadInterval\": 100,\n"
    "          \"ids\": [\n"
    "            {\n"
    "              \"id\": \"01035004\"\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035005\"\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035006\"\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035007\"\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035104\"\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035105\"\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035106\"\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035107\"\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035204\"\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035205\"\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035206\"\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035207\"\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035304\"\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035305\"\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035306\"\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035307\"\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035504\"\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035505\"\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035506\"\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035507\"\n"
    "            }\n"
    "          ]\n"
    "        }\n"
    "      ],\n"
    "      \"dataItems\": [\n"
    "        {\n"
    "          \"id\": \"010302\",\n"
    "          \"name\": \"设备状态\",\n"
    "          \"type\": \"STATUS\"\n"
    "        },\n"
    "        {\n"
    "          \"id\": \"010303\",\n"
    "          \"name\": \"进给速度\",\n"
    "          \"type\": \"FEED_SPEED\"\n"
    "        },\n"
    "        {\n"
    "          \"id\": \"010305\",\n"
    "          \"name\": \"进给倍率\",\n"
    "          \"type\": \"FEED_OVERRIDE\"\n"
    "        },\n"
    "        {\n"
    "          \"id\": \"010306\",\n"
    "          \"name\": \"主轴倍率\",\n"
    "          \"type\": \"SPINDLE_OVERRIDE\"\n"
    "        },\n"
    "        {\n"
    "          \"id\": \"010307\",\n"
    "          \"name\": \"加工计件\",\n"
    "          \"type\": \"PART_COUNT\"\n"
    "        },\n"
    "        {\n"
    "          \"id\": \"010309\",\n"
    "          \"name\": \"加工模式\",\n"
    "          \"type\": \"MACHINING_MODE\"\n"
    "        }\n"
    "      ],\n"
    "      \"components\": [\n"
    "        {\n"
    "          \"type\": \"AXIS\",\n"
    "          \"number\": \"X\",\n"
    "          \"id\": \"010350\",\n"
    "          \"name\": \"X轴\",\n"
    "          \"description\": \"\",\n"
    "          \"configs\": [\n"
    "            {\n"
    "              \"id\": \"01035001\",\n"
    "              \"name\": \"轴名\",\n"
    "              \"type\": \"NAME\",\n"
    "              \"value\": \"X\"\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035002\",\n"
    "              \"name\": \"轴号\",\n"
    "              \"type\": \"NUMBER\",\n"
    "              \"value\": 0\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035003\",\n"
    "              \"name\": \"轴类型\",\n"
    "              \"type\": \"TYPE\",\n"
    "              \"value\": \"linear\"\n"
    "            }\n"
    "          ],\n"
    "          \"components\": [\n"
    "            {\n"
    "              \"type\": \"SERVO_DRIVER\",\n"
    "              \"id\": \"01035020\",\n"
    "              \"name\": \"驱动器\",\n"
    "              \"description\": \"\",\n"
    "              \"dataItems\": [\n"
    "                {\n"
    "                  \"id\": \"0103502001\",\n"
    "                  \"name\": \"指令位置\",\n"
    "                  \"type\": \"POSITION\"\n"
    "                },\n"
    "                {\n"
    "                  \"id\": \"0103502003\",\n"
    "                  \"name\": \"指令速度\",\n"
    "                  \"type\": \"SPEED\"\n"
    "                }\n"
    "              ]\n"
    "            },\n"
    "            {\n"
    "              \"type\": \"MOTOR\",\n"
    "              \"id\": \"01035021\",\n"
    "              \"name\": \"电机\",\n"
    "              \"description\": \"\",\n"
    "              \"dataItems\": [\n"
    "                {\n"
    "                  \"id\": \"0103502101\",\n"
    "                  \"name\": \"负载电流\",\n"
    "                  \"type\": \"CURRENT\"\n"
    "                }\n"
    "              ]\n"
    "            },\n"
    "            {\n"
    "              \"type\": \"SCREW\",\n"
    "              \"id\": \"01035022\",\n"
    "              \"name\": \"丝杠\",\n"
    "              \"description\": \"\",\n"
    "              \"dataItems\": [\n"
    "                {\n"
    "                  \"id\": \"0103502201\",\n"
    "                  \"name\": \"实际位置\",\n"
    "                  \"type\": \"POSITION\"\n"
    "                },\n"
    "                {\n"
    "                  \"id\": \"0103502202\",\n"
    "                  \"name\": \"实际速度\",\n"
    "                  \"type\": \"SPEED\"\n"
    "                }\n"
    "              ]\n"
    "            }\n"
    "          ],\n"
    "          \"dataItems\": [\n"
    "            {\n"
    "              \"id\": \"01035004\",\n"
    "              \"name\": \"功率\",\n"
    "              \"type\": \"POWER\",\n"
    "              \"number\": \"1\"\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035005\",\n"
    "              \"name\": \"X向加速度\",\n"
    "              \"type\": \"ACCELERATION\",\n"
    "              \"number\": \"X\"\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035006\",\n"
    "              \"name\": \"Y向加速度\",\n"
    "              \"type\": \"ACCELERATION\",\n"
    "              \"number\": \"Y\"\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035007\",\n"
    "              \"name\": \"Z向加速度\",\n"
    "              \"type\": \"ACCELERATION\",\n"
    "              \"number\": \"Z\"\n"
    "            }\n"
    "          ]\n"
    "        },\n"
    "        {\n"
    "          \"type\": \"AXIS\",\n"
    "          \"number\": \"Y\",\n"
    "          \"id\": \"010351\",\n"
    "          \"name\": \"Y轴\",\n"
    "          \"description\": \"\",\n"
    "          \"configs\": [\n"
    "            {\n"
    "              \"id\": \"01035101\",\n"
    "              \"name\": \"轴名\",\n"
    "              \"type\": \"NAME\",\n"
    "              \"value\": \"Y\"\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035102\",\n"
    "              \"name\": \"轴号\",\n"
    "              \"type\": \"NUMBER\",\n"
    "              \"value\": 1\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035103\",\n"
    "              \"name\": \"轴类型\",\n"
    "              \"type\": \"TYPE\",\n"
    "              \"value\": \"linear\"\n"
    "            }\n"
    "          ],\n"
    "          \"components\": [\n"
    "            {\n"
    "              \"type\": \"SERVO_DRIVER\",\n"
    "              \"id\": \"01035120\",\n"
    "              \"name\": \"驱动器\",\n"
    "              \"description\": \"\",\n"
    "              \"dataItems\": [\n"
    "                {\n"
    "                  \"id\": \"0103512001\",\n"
    "                  \"name\": \"指令位置\",\n"
    "                  \"type\": \"POSITION\"\n"
    "                },\n"
    "                {\n"
    "                  \"id\": \"0103512003\",\n"
    "                  \"name\": \"指令速度\",\n"
    "                  \"type\": \"SPEED\"\n"
    "                }\n"
    "              ]\n"
    "            },\n"
    "            {\n"
    "              \"type\": \"MOTOR\",\n"
    "              \"id\": \"01035121\",\n"
    "              \"name\": \"电机\",\n"
    "              \"description\": \"\",\n"
    "              \"dataItems\": [\n"
    "                {\n"
    "                  \"id\": \"0103512101\",\n"
    "                  \"name\": \"负载电流\",\n"
    "                  \"type\": \"CURRENT\"\n"
    "                }\n"
    "              ]\n"
    "            },\n"
    "            {\n"
    "              \"type\": \"SCREW\",\n"
    "              \"id\": \"01035122\",\n"
    "              \"name\": \"丝杠\",\n"
    "              \"description\": \"\",\n"
    "              \"dataItems\": [\n"
    "                {\n"
    "                  \"id\": \"0103512201\",\n"
    "                  \"name\": \"实际位置\",\n"
    "                  \"type\": \"POSITION\"\n"
    "                },\n"
    "                {\n"
    "                  \"id\": \"0103512202\",\n"
    "                  \"name\": \"实际速度\",\n"
    "                  \"type\": \"SPEED\"\n"
    "                }\n"
    "              ]\n"
    "            }\n"
    "          ],\n"
    "          \"dataItems\": [\n"
    "            {\n"
    "              \"id\": \"01035104\",\n"
    "              \"name\": \"功率\",\n"
    "              \"type\": \"POWER\",\n"
    "              \"number\": \"1\"\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035105\",\n"
    "              \"name\": \"X向加速度\",\n"
    "              \"type\": \"ACCELERATION\",\n"
    "              \"number\": \"X\"\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035106\",\n"
    "              \"name\": \"Y向加速度\",\n"
    "              \"type\": \"ACCELERATION\",\n"
    "              \"number\": \"Y\"\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035107\",\n"
    "              \"name\": \"Z向加速度\",\n"
    "              \"type\": \"ACCELERATION\",\n"
    "              \"number\": \"Z\"\n"
    "            }\n"
    "          ]\n"
    "        },\n"
    "        {\n"
    "          \"type\": \"AXIS\",\n"
    "          \"number\": \"Z\",\n"
    "          \"id\": \"010352\",\n"
    "          \"name\": \"Z轴\",\n"
    "          \"description\": \"\",\n"
    "          \"configs\": [\n"
    "            {\n"
    "              \"id\": \"01035201\",\n"
    "              \"name\": \"轴名\",\n"
    "              \"type\": \"NAME\",\n"
    "              \"value\": \"Z\"\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035202\",\n"
    "              \"name\": \"轴号\",\n"
    "              \"type\": \"NUMBER\",\n"
    "              \"value\": 2\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035203\",\n"
    "              \"name\": \"轴类型\",\n"
    "              \"type\": \"TYPE\",\n"
    "              \"value\": \"linear\"\n"
    "            }\n"
    "          ],\n"
    "          \"components\": [\n"
    "            {\n"
    "              \"type\": \"SERVO_DRIVER\",\n"
    "              \"id\": \"01035220\",\n"
    "              \"name\": \"驱动器\",\n"
    "              \"description\": \"\",\n"
    "              \"dataItems\": [\n"
    "                {\n"
    "                  \"id\": \"0103522001\",\n"
    "                  \"name\": \"指令位置\",\n"
    "                  \"type\": \"POSITION\"\n"
    "                },\n"
    "                {\n"
    "                  \"id\": \"0103522003\",\n"
    "                  \"name\": \"指令速度\",\n"
    "                  \"type\": \"SPEED\"\n"
    "                }\n"
    "              ]\n"
    "            },\n"
    "            {\n"
    "              \"type\": \"MOTOR\",\n"
    "              \"id\": \"01035221\",\n"
    "              \"name\": \"电机\",\n"
    "              \"description\": \"\",\n"
    "              \"dataItems\": [\n"
    "                {\n"
    "                  \"id\": \"0103522101\",\n"
    "                  \"name\": \"负载电流\",\n"
    "                  \"type\": \"CURRENT\"\n"
    "                }\n"
    "              ]\n"
    "            },\n"
    "            {\n"
    "              \"type\": \"SCREW\",\n"
    "              \"id\": \"01035222\",\n"
    "              \"name\": \"丝杠\",\n"
    "              \"description\": \"\",\n"
    "              \"dataItems\": [\n"
    "                {\n"
    "                  \"id\": \"0103522201\",\n"
    "                  \"name\": \"实际位置\",\n"
    "                  \"type\": \"POSITION\"\n"
    "                },\n"
    "                {\n"
    "                  \"id\": \"0103522202\",\n"
    "                  \"name\": \"实际速度\",\n"
    "                  \"type\": \"SPEED\"\n"
    "                }\n"
    "              ]\n"
    "            }\n"
    "          ],\n"
    "          \"dataItems\": [\n"
    "            {\n"
    "              \"id\": \"01035204\",\n"
    "              \"name\": \"功率\",\n"
    "              \"type\": \"POWER\",\n"
    "              \"number\": \"1\"\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035205\",\n"
    "              \"name\": \"X向加速度\",\n"
    "              \"type\": \"ACCELERATION\",\n"
    "              \"number\": \"X\"\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035206\",\n"
    "              \"name\": \"Y向加速度\",\n"
    "              \"type\": \"ACCELERATION\",\n"
    "              \"number\": \"Y\"\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035207\",\n"
    "              \"name\": \"Z向加速度\",\n"
    "              \"type\": \"ACCELERATION\",\n"
    "              \"number\": \"Z\"\n"
    "            }\n"
    "          ]\n"
    "        },\n"
    "        {\n"
    "          \"type\": \"AXIS\",\n"
    "          \"number\": \"C\",\n"
    "          \"id\": \"010353\",\n"
    "          \"name\": \"C轴\",\n"
    "          \"description\": \"\",\n"
    "          \"configs\": [\n"
    "            {\n"
    "              \"id\": \"01035301\",\n"
    "              \"name\": \"轴名\",\n"
    "              \"type\": \"NAME\",\n"
    "              \"value\": \"C\"\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035302\",\n"
    "              \"name\": \"轴号\",\n"
    "              \"type\": \"NUMBER\",\n"
    "              \"value\": 5\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035303\",\n"
    "              \"name\": \"轴类型\",\n"
    "              \"type\": \"TYPE\",\n"
    "              \"value\": \"rotary\"\n"
    "            }\n"
    "          ],\n"
    "          \"components\": [\n"
    "            {\n"
    "              \"type\": \"SERVO_DRIVER\",\n"
    "              \"id\": \"01035320\",\n"
    "              \"name\": \"C轴驱动器\",\n"
    "              \"description\": \"\",\n"
    "              \"dataItems\": [\n"
    "                {\n"
    "                  \"id\": \"0103532001\",\n"
    "                  \"name\": \"指令位置\",\n"
    "                  \"type\": \"POSITION\"\n"
    "                },\n"
    "                {\n"
    "                  \"id\": \"0103532002\",\n"
    "                  \"name\": \"指令速度\",\n"
    "                  \"type\": \"SPEED\"\n"
    "                }\n"
    "              ]\n"
    "            },\n"
    "            {\n"
    "              \"type\": \"MOTOR\",\n"
    "              \"id\": \"01035321\",\n"
    "              \"name\": \"C轴电机\",\n"
    "              \"description\": \"\",\n"
    "              \"dataItems\": [\n"
    "                {\n"
    "                  \"id\": \"0103532101\",\n"
    "                  \"name\": \"实际位置\",\n"
    "                  \"type\": \"POSITION\"\n"
    "                },\n"
    "                {\n"
    "                  \"id\": \"0103532102\",\n"
    "                  \"name\": \"实际速度\",\n"
    "                  \"type\": \"SPEED\"\n"
    "                },\n"
    "                {\n"
    "                  \"id\": \"0103532103\",\n"
    "                  \"name\": \"负载电流\",\n"
    "                  \"type\": \"CURRENT\"\n"
    "                }\n"
    "              ]\n"
    "            }\n"
    "          ],\n"
    "          \"dataItems\": [\n"
    "            {\n"
    "              \"id\": \"01035304\",\n"
    "              \"name\": \"功率\",\n"
    "              \"type\": \"POWER\",\n"
    "              \"number\": \"1\"\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035305\",\n"
    "              \"name\": \"X向加速度\",\n"
    "              \"type\": \"ACCELERATION\",\n"
    "              \"number\": \"X\"\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035306\",\n"
    "              \"name\": \"Y向加速度\",\n"
    "              \"type\": \"ACCELERATION\",\n"
    "              \"number\": \"Y\"\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035307\",\n"
    "              \"name\": \"Z向加速度\",\n"
    "              \"type\": \"ACCELERATION\",\n"
    "              \"number\": \"Z\"\n"
    "            }\n"
    "          ]\n"
    "        },\n"
    "        {\n"
    "          \"type\": \"AXIS\",\n"
    "          \"number\": \"S\",\n"
    "          \"id\": \"010355\",\n"
    "          \"name\": \"主轴\",\n"
    "          \"description\": \"\",\n"
    "          \"configs\": [\n"
    "            {\n"
    "              \"id\": \"01035501\",\n"
    "              \"name\": \"轴名\",\n"
    "              \"type\": \"NAME\",\n"
    "              \"value\": \"S\"\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035502\",\n"
    "              \"name\": \"轴号\",\n"
    "              \"type\": \"NUMBER\",\n"
    "              \"value\": 6\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035503\",\n"
    "              \"name\": \"轴类型\",\n"
    "              \"type\": \"TYPE\",\n"
    "              \"value\": \"rotary\"\n"
    "            }\n"
    "          ],\n"
    "          \"dataItems\": [\n"
    "            {\n"
    "              \"id\": \"01035504\",\n"
    "              \"name\": \"功率\",\n"
    "              \"type\": \"POWER\",\n"
    "              \"number\": \"1\"\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035505\",\n"
    "              \"name\": \"X向加速度\",\n"
    "              \"type\": \"ACCELERATION\",\n"
    "              \"number\": \"X\"\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035506\",\n"
    "              \"name\": \"Y向加速度\",\n"
    "              \"type\": \"ACCELERATION\",\n"
    "              \"number\": \"Y\"\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035507\",\n"
    "              \"name\": \"Z向加速度\",\n"
    "              \"type\": \"ACCELERATION\",\n"
    "              \"number\": \"Z\"\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035509\",\n"
    "              \"name\": \"转速\",\n"
    "              \"type\": \"SPEED\"\n"
    "            }\n"
    "          ],\n"
    "          \"components\": [\n"
    "            {\n"
    "              \"type\": \"SERVO_DRIVER\",\n"
    "              \"id\": \"01035520\",\n"
    "              \"name\": \"主轴驱动器\",\n"
    "              \"description\": \"\",\n"
    "              \"dataItems\": [\n"
    "                {\n"
    "                  \"id\": \"0103552001\",\n"
    "                  \"name\": \"指令位置\",\n"
    "                  \"type\": \"POSITION\"\n"
    "                },\n"
    "                {\n"
    "                  \"id\": \"0103552002\",\n"
    "                  \"name\": \"指令速度\",\n"
    "                  \"type\": \"SPEED\"\n"
    "                }\n"
    "              ]\n"
    "            },\n"
    "            {\n"
    "              \"type\": \"MOTOR\",\n"
    "              \"id\": \"01035521\",\n"
    "              \"name\": \"主轴电机\",\n"
    "              \"description\": \"\",\n"
    "              \"dataItems\": [\n"
    "                {\n"
    "                  \"id\": \"0103552101\",\n"
    "                  \"name\": \"实际位置\",\n"
    "                  \"type\": \"POSITION\"\n"
    "                },\n"
    "                {\n"
    "                  \"id\": \"0103552102\",\n"
    "                  \"name\": \"实际速度\",\n"
    "                  \"type\": \"SPEED\"\n"
    "                },\n"
    "                {\n"
    "                  \"id\": \"0103552103\",\n"
    "                  \"name\": \"负载电流\",\n"
    "                  \"type\": \"CURRENT\"\n"
    "                }\n"
    "              ]\n"
    "            }\n"
    "          ]\n"
    "        },\n"
    "        {\n"
    "          \"type\": \"CONTROLLER\",\n"
    "          \"id\": \"010354\",\n"
    "          \"name\": \"数控系统\",\n"
    "          \"description\": \"\",\n"
    "          \"configs\": [\n"
    "            {\n"
    "              \"id\": \"01035404\",\n"
    "              \"type\": \"TOOL_PARAM\",\n"
    "              \"name\": \"刀具参数\",\n"
    "              \"dataType\": \"LIST\",\n"
    "              \"settable\": true\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035405\",\n"
    "              \"type\": \"COORDINATE\",\n"
    "              \"name\": \"坐标系\",\n"
    "              \"dataType\": \"LIST\",\n"
    "              \"settable\": true\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035406\",\n"
    "              \"type\": \"CONSOLE\",\n"
    "              \"name\": \"指令\",\n"
    "              \"settable\": true\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035407\",\n"
    "              \"type\": \"PARAMETER\",\n"
    "              \"name\": \"参数\",\n"
    "              \"dataType\": \"LIST\",\n"
    "              \"settable\": true\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035408\",\n"
    "              \"type\": \"FILE\",\n"
    "              \"name\": \"G代码文件\",\n"
    "              \"dataType\": \"HASH\",\n"
    "              \"settable\": true\n"
    "            }\n"
    "          ],\n"
    "          \"dataItems\": [\n"
    "            {\n"
    "              \"id\": \"01035409\",\n"
    "              \"type\": \"PROGRAM\",\n"
    "              \"name\": \"主程序名\"\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035410\",\n"
    "              \"type\": \"SUBPROGRAM\",\n"
    "              \"name\": \"子程序名\"\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035411\",\n"
    "              \"type\": \"LINE_NUMBER\",\n"
    "              \"name\": \"指令行号\"\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035412\",\n"
    "              \"type\": \"WARNING\",\n"
    "              \"name\": \"报警\"\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035413\",\n"
    "              \"type\": \"TOOL_NUMBER\",\n"
    "              \"name\": \"刀具号\"\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035414\",\n"
    "              \"type\": \"PROGRAM_NUMBER\",\n"
    "              \"name\": \"程序号\"\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035415\",\n"
    "              \"type\": \"VARIABLE\",\n"
    "              \"number\": \"PROGID_MAP\",\n"
    "              \"name\": \"程序ID映射表\"\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035420\",\n"
    "              \"type\": \"VARIABLE\",\n"
    "              \"number\": \"EVENT\",\n"
    "              \"name\": \"事件\"\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035430\",\n"
    "              \"type\": \"VARIABLE\",\n"
    "              \"number\": \"REG_X\",\n"
    "              \"name\": \"寄存器X\",\n"
    "              \"dataType\": \"LIST\",\n"
    "              \"settable\": true\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035431\",\n"
    "              \"type\": \"VARIABLE\",\n"
    "              \"number\": \"REG_Y\",\n"
    "              \"name\": \"寄存器Y\",\n"
    "              \"dataType\": \"LIST\",\n"
    "              \"settable\": true\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035432\",\n"
    "              \"type\": \"VARIABLE\",\n"
    "              \"number\": \"REG_F\",\n"
    "              \"name\": \"寄存器F\",\n"
    "              \"dataType\": \"LIST\",\n"
    "              \"settable\": true\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035433\",\n"
    "              \"type\": \"VARIABLE\",\n"
    "              \"number\": \"REG_G\",\n"
    "              \"name\": \"寄存器G\",\n"
    "              \"dataType\": \"LIST\",\n"
    "              \"settable\": true\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035434\",\n"
    "              \"type\": \"VARIABLE\",\n"
    "              \"number\": \"REG_R\",\n"
    "              \"name\": \"寄存器R\",\n"
    "              \"dataType\": \"LIST\",\n"
    "              \"settable\": true\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035435\",\n"
    "              \"type\": \"VARIABLE\",\n"
    "              \"number\": \"REG_W\",\n"
    "              \"name\": \"寄存器W\",\n"
    "              \"dataType\": \"LIST\",\n"
    "              \"settable\": true\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035436\",\n"
    "              \"type\": \"VARIABLE\",\n"
    "              \"number\": \"REG_D\",\n"
    "              \"name\": \"寄存器D\",\n"
    "              \"dataType\": \"LIST\",\n"
    "              \"settable\": true\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035437\",\n"
    "              \"type\": \"VARIABLE\",\n"
    "              \"number\": \"REG_B\",\n"
    "              \"name\": \"寄存器B\",\n"
    "              \"dataType\": \"LIST\",\n"
    "              \"settable\": true\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035438\",\n"
    "              \"type\": \"VARIABLE\",\n"
    "              \"number\": \"REG_P\",\n"
    "              \"name\": \"寄存器P\",\n"
    "              \"dataType\": \"LIST\",\n"
    "              \"settable\": true\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035439\",\n"
    "              \"type\": \"VARIABLE\",\n"
    "              \"number\": \"REG_I\",\n"
    "              \"name\": \"寄存器I\",\n"
    "              \"dataType\": \"LIST\",\n"
    "              \"settable\": true\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035440\",\n"
    "              \"type\": \"VARIABLE\",\n"
    "              \"number\": \"REG_Q\",\n"
    "              \"name\": \"寄存器Q\",\n"
    "              \"dataType\": \"LIST\",\n"
    "              \"settable\": true\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035441\",\n"
    "              \"type\": \"VARIABLE\",\n"
    "              \"number\": \"REG_K\",\n"
    "              \"name\": \"寄存器K\",\n"
    "              \"dataType\": \"LIST\",\n"
    "              \"settable\": true\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035442\",\n"
    "              \"type\": \"VARIABLE\",\n"
    "              \"number\": \"REG_T\",\n"
    "              \"name\": \"寄存器T\",\n"
    "              \"dataType\": \"LIST\",\n"
    "              \"settable\": true\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035443\",\n"
    "              \"type\": \"VARIABLE\",\n"
    "              \"number\": \"REG_C\",\n"
    "              \"name\": \"寄存器C\",\n"
    "              \"dataType\": \"LIST\",\n"
    "              \"settable\": true\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035450\",\n"
    "              \"type\": \"VARIABLE\",\n"
    "              \"number\": \"CHAN_0\",\n"
    "              \"name\": \"通道0数据\",\n"
    "              \"dataType\": \"LIST\",\n"
    "              \"settable\": true\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035455\",\n"
    "              \"type\": \"VARIABLE\",\n"
    "              \"number\": \"AXIS_0\",\n"
    "              \"name\": \"轴0数据\",\n"
    "              \"dataType\": \"LIST\"\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035456\",\n"
    "              \"type\": \"VARIABLE\",\n"
    "              \"number\": \"AXIS_1\",\n"
    "              \"name\": \"轴1数据\",\n"
    "              \"dataType\": \"LIST\"\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035457\",\n"
    "              \"type\": \"VARIABLE\",\n"
    "              \"number\": \"AXIS_2\",\n"
    "              \"name\": \"轴2数据\",\n"
    "              \"dataType\": \"LIST\"\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035460\",\n"
    "              \"type\": \"VARIABLE\",\n"
    "              \"number\": \"AXIS_5\",\n"
    "              \"name\": \"轴5数据\",\n"
    "              \"dataType\": \"LIST\"\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035470\",\n"
    "              \"type\": \"VARIABLE\",\n"
    "              \"number\": \"SYS\",\n"
    "              \"name\": \"系统数据\",\n"
    "              \"dataType\": \"LIST\"\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035471\",\n"
    "              \"type\": \"VARIABLE\",\n"
    "              \"number\": \"MACRO\",\n"
    "              \"name\": \"宏变量\",\n"
    "              \"dataType\": \"LIST\",\n"
    "              \"settable\": true\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035472\",\n"
    "              \"type\": \"VARIABLE\",\n"
    "              \"number\": \"VAR_AXIS\",\n"
    "              \"name\": \"轴变量\",\n"
    "              \"dataType\": \"LIST\",\n"
    "              \"settable\": true\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035478\",\n"
    "              \"type\": \"VARIABLE\",\n"
    "              \"number\": \"VAR_CHAN_0\",\n"
    "              \"name\": \"通道变量\",\n"
    "              \"dataType\": \"LIST\",\n"
    "              \"settable\": true\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035482\",\n"
    "              \"type\": \"VARIABLE\",\n"
    "              \"number\": \"VAR_SYS\",\n"
    "              \"name\": \"系统变量\",\n"
    "              \"dataType\": \"LIST\",\n"
    "              \"settable\": true\n"
    "            },\n"
    "            {\n"
    "              \"id\": \"01035483\",\n"
    "              \"type\": \"VARIABLE\",\n"
    "              \"number\": \"VAR_SYSF\",\n"
    "              \"name\": \"浮点系统变量\",\n"
    "              \"dataType\": \"LIST\",\n"
    "              \"settable\": true\n"
    "            }\n"
    "          ]\n"
    "        }\n"
    "      ]\n"
    "    }\n"
    "  ]\n"
    "}\n";

const char *ncl_demo_device_model(void)
{
    return kDeviceModel;
}
